### ISSUE TITLE
No Login after update and reboot

### ISSUE THREAD

**Issue by DasJott** [arcolinux/arcolinux-xfce#4]
I installed Arcolinux in a virtual machine.
Everything worked fine, except pamac needed to be installed manually, but okay.

Being in Pamac then I made all updates. After the reboot I landed on the login screen. Typing in the (correct) password first lead to a black screen and after about a second I got back to the login screen.
That was an endless game and the system simply was unusable.

Happened several times and always exactly the same:
Installation, updating, broken.

Just wanted to let you know.

**Comment by arcolinuxz** [comment]
Hi Das Jott,

Only Xfce has issues now on July 2021 when you try installing it in
Virtualbox

Vmware is fine.
Qemu is fine.

Subscribe to our Youtube channel.
The solution was out there since 10/07/2021 if this is what you are looking
for. It does sound like it.


https://youtu.be/NLCSiB_yNmM

Cheers

erik

**Comment by DasJott** [comment]
Hey Erik!

I used Gnome Boxes, which uses Qemu...
I can try nonetheless.
